docker-build:
	docker build -t cr.yandex/crpamim8dasm0u97qtpf/shbr-projects:latest .

docker-run:
	docker run -it cr.yandex/crpamim8dasm0u97qtpf/shbr-projects:latest

docker-push:
	docker push cr.yandex/crpamim8dasm0u97qtpf/shbr-projects:latest
