docker-build:
	docker build -t cr.yandex/crpamim8dasm0u97qtpf/shbr-03-run-supervisor:latest .

docker-run:
	docker run -it -d --name shbr-03-run-supervisor cr.yandex/crpamim8dasm0u97qtpf/shbr-03-run-supervisor:latest

docker-push:
	docker push cr.yandex/crpamim8dasm0u97qtpf/shbr-03-run-supervisor:latest

docker-shell:
	docker exec -it shbr-03-run-supervisor /usr/bin/fish
