docker-build:
	docker build -t cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-no_screen:latest .

docker-run:
	docker run -it -d --name shbr-03-run-no_screen cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-no_screen:latest

docker-shell:
	docker exec -it shbr-03-run-no_screen /bin/bash

docker-push:
	docker push cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-no_screen:latest
