docker-build:
	docker build -t cr.yandex/crpamim8dasm0u97qtpf/shbr-03-run-no_screen:latest .

docker-run:
	docker run -it -d --name shbr-03-run-no_screen cr.yandex/crpamim8dasm0u97qtpf/shbr-03-run-no_screen:latest

docker-shell:
	docker exec -it shbr-03-run-no_screen /usr/bin/fish

docker-push:
	docker push cr.yandex/crpamim8dasm0u97qtpf/shbr-03-run-no_screen:latest
