Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vbguest.auto_update = !Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.installer_options = { allow_kernel_upgrade: Vagrant.has_plugin?("vagrant-vbguest") } # vagrant plugin install vagrant-vbguest

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = "node-#{i}"
      node.vagrant.host = "node-#{i}"

      node.vm.network "private_network", ip: "10.0.0.#{i+1}", virtualbox__intnet: "swarm"
      node.vm.network "forwarded_port", guest: 9090 + i, host: 9090 + i, host_ip: '127.0.0.1', protocol: 'tcp', auto_correct: true

      node.vm.provider "virtualbox" do |v|
        v.name = "node-#{i}"
        v.customize ["modifyvm", :id, "--groups", "/05-orchestration-swarm"]
      end

      node.vm.provision "shell" do |s|
        s.inline = <<-SHELL
          set -e
          apt-get update
          apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common fish

          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

          apt-get update
          apt-get install -y docker-ce docker-ce-cli docker-compose containerd.io
          systemctl enable docker
          systemctl start docker
          usermod -a -G docker vagrant

          chsh -s /usr/bin/fish
          sed -i  's/auth       required   pam_shells.so/auth       sufficient   pam_shells.so/g' /etc/pam.d/chsh
          su -c '/usr/bin/chsh -s /usr/bin/fish' vagrant

          mv ~/.bash_logout ~/.bash_logout.bak 2>/dev/null || true
        SHELL
        s.privileged = true
      end
    end
  end
end