docker-build:
	docker build -t cr.yandex/crpamim8dasm0u97qtpf/shbr-01-package-deb:latest .

docker-run:
	docker run -it cr.yandex/crpamim8dasm0u97qtpf/shbr-01-package-deb:latest

docker-push:
	docker push cr.yandex/crpamim8dasm0u97qtpf/shbr-01-package-deb:latest
