Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vbguest.installer_options = { allow_kernel_upgrade: true } # vagrant plugin install vagrant-vbguest
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: '127.0.0.1', protocol: 'tcp', auto_correct: true
    config.vm.network "forwarded_port", guest: 2222, host: 22022, host_ip: '127.0.0.1', protocol: 'tcp', auto_correct: true

    config.vm.define "ci" do |node|
        node.vm.box = "ubuntu/focal64"
        node.vm.hostname = "ci"
        node.vagrant.host = "ci"

        node.vm.provider "virtualbox" do |v|
            v.name = "ci"
            v.memory = 4096
            v.cpus = 4
        end

        node.vm.provision "shell" do |s|
        s.inline = <<-SHELL
        set -e
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        apt-get update
        apt-get install -y docker-ce docker-ce-cli docker-compose containerd.io conntrack
        systemctl enable docker
        systemctl start docker
        usermod -a -G docker vagrant

        curl -L https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube_1.22.0-0_amd64.deb > minikube_1.22.0-0_amd64.deb
        dpkg -i minikube_1.22.0-0_amd64.deb
        minikube start --driver=none

        snap install kubectl --classic
        curl -sS https://webinstall.dev/k9s | sudo -u vagrant bash

        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
        apt-get update
        apt-get install -y gitlab-runner
        usermod -a -G docker gitlab-runner
        SHELL
        s.privileged = true
        end
    end
end