Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vbguest.auto_update = !Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.installer_options = { allow_kernel_upgrade: Vagrant.has_plugin?("vagrant-vbguest") } # vagrant plugin install vagrant-vbguest
    config.vm.network "forwarded_port", guest: 30080, host: 30080, host_ip: '127.0.0.1', protocol: 'tcp', auto_correct: false
    config.vm.network "forwarded_port", guest: 10022, host: 10022, host_ip: '127.0.0.1', protocol: 'tcp', auto_correct: false

    config.vm.define "06-gitlab" do |node|
        node.vm.box = "ubuntu/jammy64"
        node.vm.hostname = "06-gitlab"
        node.vagrant.host = "06-gitlab"

        node.vm.provider "virtualbox" do |v|
            v.name = "06-gitlab"
            v.memory = 6144
            v.cpus = 5
        end

        node.vm.provision "shell" do |s|
        s.inline = <<-SHELL
        set -e
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common fish

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        apt-get update
        apt-get install -y docker-ce docker-ce-cli docker-compose containerd.io conntrack
        systemctl enable docker
        systemctl start docker
        usermod -a -G docker vagrant

        curl -L https://github.com/kubernetes/minikube/releases/download/v1.23.2/minikube_1.23.2-0_amd64.deb > minikube_1.23.2-0_amd64.deb
        dpkg -i minikube_1.23.2-0_amd64.deb
        sudo -u vagrant minikube start --driver=none

        snap install kubectl --classic
        curl -sS https://webinstall.dev/k9s | sudo -u vagrant bash

        curl -LJO "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"
        dpkg -i gitlab-runner_amd64.deb
        usermod -a -G docker gitlab-runner

        chsh -s /usr/bin/fish
        sed -i  's/auth       required   pam_shells.so/auth       sufficient   pam_shells.so/g' /etc/pam.d/chsh
        su -c '/usr/bin/chsh -s /usr/bin/fish' vagrant

        mv ~/.bash_logout ~/.bash_logout.bak 2>/dev/null || true
        SHELL
        s.privileged = true
        end
    end
end