docker-build:
	docker build -t cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-docker:latest .

docker-run:
	docker run -e PREFIX="Hello, " -d --name shbr-03-run-docker -p 10000:10000 cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-docker:latest

docker-push:
	docker push cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-docker:latest