Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vbguest.auto_update = !Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.installer_options = { allow_kernel_upgrade: Vagrant.has_plugin?("vagrant-vbguest") } # vagrant plugin install vagrant-vbguest

    config.vm.define "05-orchestration-k8s" do |node|
        node.vm.box = "ubuntu/jammy64"
        node.vm.hostname = "05-orchestration-k8s"
        node.vagrant.host = "05-orchestration-k8s"

        node.vm.provider "virtualbox" do |v|
            v.name = "05-orchestration-k8s"
            v.memory = 2560
        end

        node.vm.provision "shell" do |s|
        s.inline = <<-SHELL
        set -e
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common fish

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        apt-get update
        apt-get install -y docker-ce docker-ce-cli docker-compose containerd.io conntrack
        systemctl enable docker
        systemctl start docker
        usermod -a -G docker vagrant

        curl -L https://github.com/kubernetes/minikube/releases/download/v1.23.2/minikube_1.23.2-0_amd64.deb > minikube_1.23.2-0_amd64.deb
        dpkg -i minikube_1.23.2-0_amd64.deb

        snap install kubectl --classic
        curl -sS https://webinstall.dev/k9s | sudo -u vagrant bash

        chsh -s /usr/bin/fish
        sed -i  's/auth       required   pam_shells.so/auth       sufficient   pam_shells.so/g' /etc/pam.d/chsh
        su -c '/usr/bin/chsh -s /usr/bin/fish' vagrant

        mv ~/.bash_logout ~/.bash_logout.bak 2>/dev/null || true
        SHELL
        s.privileged = true
        end
    end
end