docker-build:
	docker build -t cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-supervisor:latest .

docker-run:
	docker run -it --name shbr-03-run-supervisor cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-supervisor:latest

docker-push:
	docker push cr.yandex/crp5udmc090nv4rpkk6c/shbr-03-run-supervisor:latest

docker-shell:
	docker exec -it shbr-03-run-supervisor /bin/bash