Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vbguest.installer_options = { allow_kernel_upgrade: true } # vagrant plugin install vagrant-vbguest

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../../projects/python", "/python"
    config.vm.synced_folder "../../projects/java", "/java"
    config.vm.synced_folder "./shbr-echo", "/shbr-echo"

    config.vm.define "03-run-systemd" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "03-run-systemd"
      node.vagrant.host = "03-run-systemd"

      node.vm.network "forwarded_port", guest: 10000, host: 10000, host_ip: '127.0.0.1', protocol: 'tcp', auto_correct: true

      node.vm.provider "virtualbox" do |v|
        v.name = "03-run-systemd"
      end

      node.vm.provision "shell" do |s|
        s.inline = <<-SHELL
          set -e
          apt-get update
          apt-get install -y golang debhelper build-essential
        SHELL
        s.privileged = true
      end
    end
end