docker-build:
	docker build -t cr.yandex/crp5udmc090nv4rpkk6c/shbr-01-package-deb:latest .

docker-run:
	docker run -it cr.yandex/crp5udmc090nv4rpkk6c/shbr-01-package-deb:latest

docker-push:
	docker push cr.yandex/crp5udmc090nv4rpkk6c/shbr-01-package-deb:latest